/* Generated by Yosys 0.9+2406 (git sha1 aafaeb66, gcc 9.3.0-1 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -fPIC -Os) */

(* generator = "nMigen" *)
(* \nmigen.hierarchy  = "top.U$$0" *)
module \U$$0 (n64__ad_oe, n64__ad_i, n64__read, n64__ale_l, n64__ale_h, rst, clk, sdram__data_oe, sdram__data_out, sdram__data_in, sdram__cke, sdram__addr, sdram__ba, sdram__cs, sdram__ras, sdram__cas, sdram__we, sdram__dqm, n64__ad_o);
  (* src = "top.py:40" *)
  wire \$1 ;
  (* src = "top.py:44" *)
  wire \$11 ;
  (* src = "top.py:44" *)
  wire \$13 ;
  (* src = "top.py:46" *)
  wire [16:0] \$15 ;
  (* src = "top.py:46" *)
  wire [16:0] \$16 ;
  (* src = "top.py:59" *)
  wire [16:0] \$18 ;
  (* src = "top.py:59" *)
  wire [16:0] \$19 ;
  (* src = "top.py:44" *)
  wire \$21 ;
  (* src = "top.py:54" *)
  wire \$3 ;
  (* src = "top.py:40" *)
  wire \$5 ;
  (* src = "top.py:44" *)
  wire \$7 ;
  (* src = "top.py:54" *)
  wire \$9 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:18" *)
  reg [1:0] \U$$1_cmd  = 2'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:18" *)
  reg [1:0] \U$$1_cmd$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:26" *)
  wire [1:0] \U$$1_cmd_ack ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:22" *)
  wire \U$$1_rd_valid ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:24" *)
  wire \U$$1_wr_valid_early ;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input clk;
  (* src = "top.py:32" *)
  reg [15:0] counter = 16'h0000;
  (* src = "top.py:32" *)
  reg [15:0] \counter$next ;
  (* src = "top.py:33" *)
  reg [15:0] data = 16'h0000;
  (* src = "top.py:33" *)
  reg [15:0] \data$next ;
  (* src = "top.py:37" *)
  reg [1:0] fsm_state = 2'h0;
  (* src = "top.py:37" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  input [15:0] n64__ad_i;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  output [15:0] n64__ad_o;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  output n64__ad_oe;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  input n64__ale_h;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  input n64__ale_l;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  input n64__read;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input rst;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output [12:0] sdram__addr;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output [1:0] sdram__ba;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__cas;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__cke;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__cs;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  input [15:0] sdram__data_in;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__data_oe;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output [15:0] sdram__data_out;
  reg [15:0] sdram__data_out;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output [1:0] sdram__dqm;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__ras;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__we;
  (* src = "top.py:35" *)
  reg write_happened = 1'h0;
  (* src = "top.py:35" *)
  reg \write_happened$next ;
  assign \$9  = \U$$1_cmd_ack  == (* src = "top.py:54" *) 2'h3;
  assign \$11  = \U$$1_wr_valid_early  | (* src = "top.py:44" *) sdram__data_oe;
  assign \$13  = \U$$1_wr_valid_early  | (* src = "top.py:44" *) sdram__data_oe;
  assign \$16  = counter + (* src = "top.py:46" *) 1'h1;
  assign \$1  = \U$$1_cmd_ack  == (* src = "top.py:40" *) 1'h1;
  assign \$19  = counter + (* src = "top.py:59" *) 1'h1;
  assign \$21  = \U$$1_wr_valid_early  | (* src = "top.py:44" *) sdram__data_oe;
  assign \$3  = \U$$1_cmd_ack  == (* src = "top.py:54" *) 2'h3;
  assign \$5  = \U$$1_cmd_ack  == (* src = "top.py:40" *) 1'h1;
  assign \$7  = \U$$1_wr_valid_early  | (* src = "top.py:44" *) sdram__data_oe;
  always @(posedge clk)
      data <= \data$next ;
  always @(posedge clk)
      counter <= \counter$next ;
  always @(posedge clk)
      write_happened <= \write_happened$next ;
  always @(posedge clk)
      fsm_state <= \fsm_state$next ;
  always @(posedge clk)
      \U$$1_cmd  <= \U$$1_cmd$next ;
  \U$$0$1  \U$$0  (
    .clk(clk),
    .n64__ad_i(n64__ad_i),
    .n64__ad_o(n64__ad_o),
    .n64__ad_oe(n64__ad_oe),
    .n64__ale_h(n64__ale_h),
    .n64__ale_l(n64__ale_l),
    .n64__read(n64__read),
    .rst(rst)
  );
  \U$$1  \U$$1  (
    .clk(clk),
    .cmd(\U$$1_cmd ),
    .cmd_ack(\U$$1_cmd_ack ),
    .rd_valid(\U$$1_rd_valid ),
    .sdram__addr(sdram__addr),
    .sdram__ba(sdram__ba),
    .sdram__cas(sdram__cas),
    .sdram__cke(sdram__cke),
    .sdram__cs(sdram__cs),
    .sdram__data_oe(sdram__data_oe),
    .sdram__dqm(sdram__dqm),
    .sdram__ras(sdram__ras),
    .sdram__we(sdram__we),
    .wr_valid_early(\U$$1_wr_valid_early )
  );
  always @* begin
    \U$$1_cmd$next  = \U$$1_cmd ;
    (* src = "top.py:37" *)
    casez (fsm_state)
      /* src = "top.py:38" */
      /* \nmigen.decoding  = "wait_sdram/0" */
      2'h0:
        begin
          \U$$1_cmd$next  = 2'h1;
          (* src = "top.py:40" *)
          casez (\$1 )
            /* src = "top.py:40" */
            1'h1:
                \U$$1_cmd$next  = 2'h0;
          endcase
        end
      /* src = "top.py:52" */
      /* \nmigen.decoding  = "read_req/2" */
      2'h2:
        begin
          \U$$1_cmd$next  = 2'h3;
          (* src = "top.py:54" *)
          casez (\$3 )
            /* src = "top.py:54" */
            1'h1:
                \U$$1_cmd$next  = 2'h0;
          endcase
        end
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \U$$1_cmd$next  = 2'h0;
    endcase
  end
  always @* begin
    \fsm_state$next  = fsm_state;
    (* src = "top.py:37" *)
    casez (fsm_state)
      /* src = "top.py:38" */
      /* \nmigen.decoding  = "wait_sdram/0" */
      2'h0:
          (* src = "top.py:40" *)
          casez (\$5 )
            /* src = "top.py:40" */
            1'h1:
                \fsm_state$next  = 2'h1;
          endcase
      /* src = "top.py:43" */
      /* \nmigen.decoding  = "write/1" */
      2'h1:
          (* src = "top.py:44" *)
          casez (\$7 )
            /* src = "top.py:44" */
            1'h1:
                /* empty */;
            /* src = "top.py:48" */
            default:
                (* src = "top.py:49" *)
                casez (write_happened)
                  /* src = "top.py:49" */
                  1'h1:
                      \fsm_state$next  = 2'h2;
                endcase
          endcase
      /* src = "top.py:52" */
      /* \nmigen.decoding  = "read_req/2" */
      2'h2:
          (* src = "top.py:54" *)
          casez (\$9 )
            /* src = "top.py:54" */
            1'h1:
                \fsm_state$next  = 2'h3;
          endcase
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 2'h0;
    endcase
  end
  always @* begin
    \write_happened$next  = write_happened;
    (* src = "top.py:37" *)
    casez (fsm_state)
      /* src = "top.py:43" */
      /* \nmigen.decoding  = "write/1" */
      2'h1:
          (* src = "top.py:44" *)
          casez (\$11 )
            /* src = "top.py:44" */
            1'h1:
                \write_happened$next  = 1'h1;
            /* src = "top.py:48" */
            default:
                (* src = "top.py:49" *)
                casez (write_happened)
                  /* src = "top.py:49" */
                  1'h1:
                      \write_happened$next  = 1'h0;
                endcase
          endcase
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \write_happened$next  = 1'h0;
    endcase
  end
  always @* begin
    \counter$next  = counter;
    (* src = "top.py:37" *)
    casez (fsm_state)
      /* src = "top.py:43" */
      /* \nmigen.decoding  = "write/1" */
      2'h1:
          (* src = "top.py:44" *)
          casez (\$13 )
            /* src = "top.py:44" */
            1'h1:
                \counter$next  = \$15 [15:0];
          endcase
      /* src = "top.py:57" */
      /* \nmigen.decoding  = "read/3" */
      2'h3:
          (* src = "top.py:58" *)
          casez (\U$$1_rd_valid )
            /* src = "top.py:58" */
            1'h1:
                \counter$next  = \$18 [15:0];
          endcase
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \counter$next  = 16'h0000;
    endcase
  end
  always @* begin
    sdram__data_out = 16'h0000;
    (* src = "top.py:37" *)
    casez (fsm_state)
      /* src = "top.py:43" */
      /* \nmigen.decoding  = "write/1" */
      2'h1:
          (* src = "top.py:44" *)
          casez (\$21 )
            /* src = "top.py:44" */
            1'h1:
                sdram__data_out = counter;
          endcase
    endcase
  end
  always @* begin
    \data$next  = data;
    (* src = "top.py:37" *)
    casez (fsm_state)
      /* src = "top.py:57" */
      /* \nmigen.decoding  = "read/3" */
      2'h3:
          (* src = "top.py:58" *)
          casez (\U$$1_rd_valid )
            /* src = "top.py:58" */
            1'h1:
                \data$next  = sdram__data_in;
          endcase
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \data$next  = 16'h0000;
    endcase
  end
  assign \$15  = \$16 ;
  assign \$18  = \$19 ;
endmodule

(* generator = "nMigen" *)
(* \nmigen.hierarchy  = "top.U$$0.U$$0" *)
module \U$$0$1 (n64__ad_oe, n64__ad_i, n64__read, n64__ale_l, n64__ale_h, rst, clk, n64__ad_o);
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:25" *)
  wire [23:0] \$1 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:25" *)
  wire [23:0] \$2 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:49" *)
  wire [32:0] \$4 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:49" *)
  wire [32:0] \$5 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:27" *)
  reg [31:0] addr = 32'd0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:27" *)
  reg [31:0] \addr$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:6" *)
  wire ale_l_edge_fall;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input clk;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  input [15:0] n64__ad_i;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  output [15:0] n64__ad_o;
  reg [15:0] n64__ad_o = 16'h0000;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  reg [15:0] \n64__ad_o$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  output n64__ad_oe;
  reg n64__ad_oe = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  reg \n64__ad_oe$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  input n64__ale_h;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  input n64__ale_l;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  input n64__read;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:6" *)
  wire read_edge_fall;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input rst;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:24" *)
  reg [22:0] timer = 23'h000000;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:24" *)
  reg [22:0] \timer$next ;
  assign \$2  = timer + (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:25" *) 1'h1;
  assign \$5  = addr + (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:49" *) 2'h2;
  always @(posedge clk)
      n64__ad_o <= \n64__ad_o$next ;
  always @(posedge clk)
      n64__ad_oe <= \n64__ad_oe$next ;
  always @(posedge clk)
      addr <= \addr$next ;
  always @(posedge clk)
      timer <= \timer$next ;
  ale_l_edge ale_l_edge (
    .clk(clk),
    .fall(ale_l_edge_fall),
    .n64__ale_l(n64__ale_l),
    .rst(rst)
  );
  read_edge read_edge (
    .clk(clk),
    .fall(read_edge_fall),
    .n64__read(n64__read),
    .rst(rst)
  );
  always @* begin
    \timer$next  = \$1 [22:0];
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \timer$next  = 23'h000000;
    endcase
  end
  always @* begin
    \addr$next  = addr;
    (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:33" *)
    casez (n64__ale_l)
      /* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:33" */
      1'h1:
          (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:34" *)
          casez (n64__ale_h)
            /* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:34" */
            1'h1:
                \addr$next [31:16] = n64__ad_i;
            /* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:36" */
            default:
                \addr$next [15:0] = n64__ad_i;
          endcase
    endcase
    (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:45" *)
    casez (read_edge_fall)
      /* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:45" */
      1'h1:
          \addr$next  = \$4 [31:0];
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \addr$next  = 32'd0;
    endcase
  end
  always @* begin
    (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:45" *)
    casez (read_edge_fall)
      /* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:45" */
      1'h1:
          \n64__ad_oe$next  = 1'h1;
      /* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:50" */
      default:
          \n64__ad_oe$next  = 1'h0;
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \n64__ad_oe$next  = 1'h0;
    endcase
  end
  always @* begin
    \n64__ad_o$next  = n64__ad_o;
    (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:45" *)
    casez (read_edge_fall)
      /* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:45" */
      1'h1:
          \n64__ad_o$next  = 16'h0000;
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \n64__ad_o$next  = 16'h0000;
    endcase
  end
  assign \$1  = \$2 ;
  assign \$4  = \$5 ;
endmodule

(* generator = "nMigen" *)
(* \nmigen.hierarchy  = "top.U$$0.U$$1" *)
module \U$$1 (cmd, cmd_ack, wr_valid_early, sdram__data_oe, rd_valid, sdram__cke, sdram__addr, sdram__ba, sdram__cs, sdram__ras, sdram__cas, sdram__we, sdram__dqm, clk);
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:19" *)
  wire [23:0] addr;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input clk;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:18" *)
  input [1:0] cmd;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:26" *)
  output [1:0] cmd_ack;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:22" *)
  output rd_valid;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output [12:0] sdram__addr;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output [1:0] sdram__ba;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__cas;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__cke;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__cs;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__data_oe;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output [1:0] sdram__dqm;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__ras;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  output sdram__we;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:24" *)
  output wr_valid_early;
  sdram_16bit \U$$0  (
    .sdr_ADDR(sdram__addr),
    .sdr_BA(sdram__ba),
    .sdr_DQM(sdram__dqm),
    .sdr_data_needed_early(wr_valid_early),
    .sdr_data_oe(sdram__data_oe),
    .sdr_n_CS_WE_RAS_CAS({ sdram__cs, sdram__we, sdram__ras, sdram__cas }),
    .sys_ADDR(addr),
    .sys_CLK(clk),
    .sys_CMD(cmd),
    .sys_cmd_ack(cmd_ack),
    .sys_rd_data_valid(rd_valid)
  );
  assign addr = 24'h000000;
  assign sdram__cke = 1'h1;
endmodule

(* generator = "nMigen" *)
(* \nmigen.hierarchy  = "top.U$$0.U$$0.ale_l_edge" *)
module ale_l_edge(rst, clk, fall, n64__ale_l);
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:14" *)
  wire \$1 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:14" *)
  wire \$3 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:15" *)
  wire \$5 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:15" *)
  wire \$7 ;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input clk;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:6" *)
  output fall;
  reg fall = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:6" *)
  reg \fall$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:11" *)
  reg last = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:11" *)
  reg \last$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  input n64__ale_l;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:7" *)
  reg rise = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:7" *)
  reg \rise$next ;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input rst;
  assign \$1  = ~ (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:14" *) n64__ale_l;
  assign \$3  = \$1  & (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:14" *) last;
  assign \$5  = ~ (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:15" *) last;
  assign \$7  = n64__ale_l & (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:15" *) \$5 ;
  always @(posedge clk)
      rise <= \rise$next ;
  always @(posedge clk)
      fall <= \fall$next ;
  always @(posedge clk)
      last <= \last$next ;
  always @* begin
    \last$next  = n64__ale_l;
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \last$next  = 1'h0;
    endcase
  end
  always @* begin
    \fall$next  = \$3 ;
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \fall$next  = 1'h0;
    endcase
  end
  always @* begin
    \rise$next  = \$7 ;
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \rise$next  = 1'h0;
    endcase
  end
endmodule

(* generator = "nMigen" *)
(* \nmigen.hierarchy  = "top.n64" *)
module n64(n64_read_i, n64_write_i, n64_ale_l_i, n64_ale_h_i, rst, clk, n64_data_i);
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$1 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:103" *)
  wire [31:0] \$10 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$100 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$102 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$103 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$105 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$107 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$109 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *)
  wire [31:0] \$11 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$110 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$112 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$114 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$116 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$117 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$119 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$121 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$123 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$124 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$126 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$128 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *)
  wire [31:0] \$13 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$130 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$131 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$133 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$135 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$137 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$138 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$140 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$142 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$144 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$145 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$147 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$149 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$15 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$150 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$152 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$154 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$155 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$157 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$159 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$160 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$162 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$164 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$165 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$167 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$169 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:103" *)
  wire [31:0] \$17 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$170 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$172 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$174 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$175 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$177 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$179 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *)
  wire [31:0] \$18 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$180 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$182 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$184 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$185 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$187 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$189 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$190 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$192 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$194 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *)
  wire [16:0] \$195 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$197 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$199 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *)
  wire [31:0] \$20 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$200 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$202 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$204 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$205 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$207 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$209 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$210 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$212 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$214 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$215 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$217 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$219 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$22 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$220 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$222 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$224 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$225 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$227 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$229 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$230 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$232 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$234 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$235 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$237 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$239 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:103" *)
  wire [31:0] \$24 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$240 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$242 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$244 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$245 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$247 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$249 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *)
  wire [31:0] \$25 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$250 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$252 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$254 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$255 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$257 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$259 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$260 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$262 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$264 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$265 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$267 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$269 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$27 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$270 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$272 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$274 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$275 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$277 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$279 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$280 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$282 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$284 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$285 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$287 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$289 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:103" *)
  wire [31:0] \$29 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *)
  wire [16:0] \$290 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$292 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$294 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *)
  wire [16:0] \$295 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:103" *)
  wire [31:0] \$3 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *)
  wire [31:0] \$30 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$32 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:103" *)
  wire [31:0] \$34 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *)
  wire [31:0] \$35 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$37 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:103" *)
  wire [31:0] \$39 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *)
  wire [31:0] \$4 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *)
  wire [31:0] \$40 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$42 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:103" *)
  wire [31:0] \$44 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *)
  wire [31:0] \$45 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$47 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:103" *)
  wire [31:0] \$49 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *)
  wire [31:0] \$50 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$52 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:103" *)
  wire [31:0] \$54 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *)
  wire [31:0] \$55 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$57 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$59 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *)
  wire [31:0] \$6 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$61 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$63 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$65 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$67 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$69 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$71 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$73 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$75 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$77 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$79 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$8 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$81 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$82 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$84 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$86 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$88 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$89 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$91 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
  wire \$93 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$95 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *)
  wire [32:0] \$96 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
  wire \$98 ;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input clk;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:49" *)
  reg [15:0] counter = 16'h0000;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:49" *)
  reg [15:0] \counter$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:28" *)
  reg [31:0] cur_addr = 32'd0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:28" *)
  reg [31:0] \cur_addr$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:86" *)
  reg fsm_state = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:86" *)
  reg \fsm_state$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  output n64_ale_h_i;
  reg n64_ale_h_i = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  reg \n64_ale_h_i$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  output n64_ale_l_i;
  reg n64_ale_l_i = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  reg \n64_ale_l_i$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  output [15:0] n64_data_i;
  reg [15:0] n64_data_i = 16'h0000;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  reg [15:0] \n64_data_i$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  output n64_read_i;
  reg n64_read_i = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  reg \n64_read_i$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  output n64_write_i;
  reg n64_write_i = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  reg \n64_write_i$next ;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input rst;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:50" *)
  reg [15:0] state = 16'h0000;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:50" *)
  reg [15:0] \state$next ;
  assign \$100  = 16'h0003 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$103  = cur_addr + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *) 3'h4;
  assign \$105  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h02;
  assign \$107  = 16'h0004 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$110  = cur_addr + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *) 3'h4;
  assign \$112  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h33;
  assign \$114  = 16'h0005 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$117  = cur_addr + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *) 3'h4;
  assign \$11  = cur_addr >>> (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *) 5'h10;
  assign \$119  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h0f;
  assign \$121  = 16'h0006 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$124  = cur_addr + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *) 3'h4;
  assign \$126  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$128  = 16'h0007 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$131  = cur_addr + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *) 3'h4;
  assign \$133  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h0f;
  assign \$135  = 16'h0008 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$138  = cur_addr + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *) 3'h4;
  assign \$13  = \$11  & (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *) 16'hffff;
  assign \$140  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$142  = 16'h0009 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$145  = cur_addr + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *) 3'h4;
  assign \$147  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h00;
  assign \$150  = counter + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *) 1'h1;
  assign \$152  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h06;
  assign \$155  = counter + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *) 1'h1;
  assign \$157  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$15  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$160  = counter + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *) 1'h1;
  assign \$162  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h02;
  assign \$165  = counter + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *) 1'h1;
  assign \$167  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h02;
  assign \$170  = counter + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *) 1'h1;
  assign \$172  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h33;
  assign \$175  = counter + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *) 1'h1;
  assign \$177  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h0f;
  assign \$180  = counter + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *) 1'h1;
  assign \$182  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$185  = counter + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *) 1'h1;
  assign \$187  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h0f;
  assign \$18  = cur_addr >>> (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *) 5'h10;
  assign \$190  = counter + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *) 1'h1;
  assign \$192  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$195  = counter + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:113" *) 1'h1;
  assign \$197  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h00;
  assign \$1  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h00;
  assign \$200  = 16'h0000 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *) 1'h1;
  assign \$202  = 16'h0000 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$205  = 16'h0000 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *) 1'h1;
  assign \$207  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h06;
  assign \$20  = \$18  & (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *) 16'hffff;
  assign \$210  = 16'h0001 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *) 1'h1;
  assign \$212  = 16'h0001 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$215  = 16'h0001 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *) 1'h1;
  assign \$217  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$220  = 16'h0002 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *) 1'h1;
  assign \$222  = 16'h0002 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$225  = 16'h0002 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *) 1'h1;
  assign \$227  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h02;
  assign \$22  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h02;
  assign \$230  = 16'h0003 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *) 1'h1;
  assign \$232  = 16'h0003 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$235  = 16'h0003 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *) 1'h1;
  assign \$237  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h02;
  assign \$240  = 16'h0004 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *) 1'h1;
  assign \$242  = 16'h0004 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$245  = 16'h0004 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *) 1'h1;
  assign \$247  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h33;
  assign \$250  = 16'h0005 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *) 1'h1;
  assign \$252  = 16'h0005 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$255  = 16'h0005 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *) 1'h1;
  assign \$257  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h0f;
  assign \$25  = cur_addr & (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *) 16'hffff;
  assign \$260  = 16'h0006 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *) 1'h1;
  assign \$262  = 16'h0006 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$265  = 16'h0006 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *) 1'h1;
  assign \$267  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$270  = 16'h0007 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *) 1'h1;
  assign \$272  = 16'h0007 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$275  = 16'h0007 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *) 1'h1;
  assign \$277  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h0f;
  assign \$27  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h02;
  assign \$280  = 16'h0008 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *) 1'h1;
  assign \$282  = 16'h0008 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$285  = 16'h0008 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *) 1'h1;
  assign \$287  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$290  = 16'h0009 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:104" *) 1'h1;
  assign \$292  = 16'h0009 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$295  = 16'h0009 + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:111" *) 1'h1;
  assign \$30  = cur_addr & (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *) 16'hffff;
  assign \$32  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h33;
  assign \$35  = cur_addr & (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *) 16'hffff;
  assign \$37  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h0f;
  assign \$40  = cur_addr & (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *) 16'hffff;
  assign \$42  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$45  = cur_addr & (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *) 16'hffff;
  assign \$47  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h0f;
  assign \$4  = cur_addr >>> (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *) 5'h10;
  assign \$50  = cur_addr & (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *) 16'hffff;
  assign \$52  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$55  = cur_addr & (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:76" *) 16'hffff;
  assign \$57  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h00;
  assign \$59  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h06;
  assign \$61  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$63  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h02;
  assign \$65  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h02;
  assign \$67  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h33;
  assign \$6  = \$4  & (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:75" *) 16'hffff;
  assign \$69  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h0f;
  assign \$71  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$73  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h0f;
  assign \$75  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$77  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h00;
  assign \$79  = 16'h0000 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$82  = cur_addr + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *) 3'h4;
  assign \$84  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h06;
  assign \$86  = 16'h0001 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$8  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h06;
  assign \$89  = cur_addr + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *) 3'h4;
  assign \$91  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h03;
  assign \$93  = 16'h0002 == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *) 4'h9;
  assign \$96  = cur_addr + (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:109" *) 3'h4;
  assign \$98  = counter == (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *) 6'h02;
  always @(posedge clk)
      state <= \state$next ;
  always @(posedge clk)
      fsm_state <= \fsm_state$next ;
  always @(posedge clk)
      counter <= \counter$next ;
  always @(posedge clk)
      cur_addr <= \cur_addr$next ;
  always @(posedge clk)
      n64_write_i <= \n64_write_i$next ;
  always @(posedge clk)
      n64_ale_h_i <= \n64_ale_h_i$next ;
  always @(posedge clk)
      n64_read_i <= \n64_read_i$next ;
  always @(posedge clk)
      n64_ale_l_i <= \n64_ale_l_i$next ;
  always @(posedge clk)
      n64_data_i <= \n64_data_i$next ;
  always @* begin
    \n64_data_i$next  = n64_data_i;
    (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:86" *)
    casez (fsm_state)
      /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:87" */
      /* \nmigen.decoding  = "reset/0" */
      1'h0:
          \n64_data_i$next  = 16'h0000;
      /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:100" */
      /* \nmigen.decoding  = "wait/1" */
      1'h1:
          (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
          casez (state)
            16'h0000:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$1 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_data_i$next  = \$3 [15:0];
                endcase
            16'h0001:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$8 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_data_i$next  = \$10 [15:0];
                endcase
            16'h0002:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$15 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_data_i$next  = \$17 [15:0];
                endcase
            16'h0003:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$22 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_data_i$next  = \$24 [15:0];
                endcase
            16'h0004:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$27 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_data_i$next  = \$29 [15:0];
                endcase
            16'h0005:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$32 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_data_i$next  = \$34 [15:0];
                endcase
            16'h0006:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$37 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_data_i$next  = \$39 [15:0];
                endcase
            16'h0007:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$42 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_data_i$next  = \$44 [15:0];
                endcase
            16'h0008:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$47 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_data_i$next  = \$49 [15:0];
                endcase
            16'h????:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$52 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_data_i$next  = \$54 [15:0];
                endcase
          endcase
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \n64_data_i$next  = 16'h0000;
    endcase
  end
  always @* begin
    \n64_ale_h_i$next  = n64_ale_h_i;
    \n64_read_i$next  = n64_read_i;
    \n64_ale_l_i$next  = n64_ale_l_i;
    (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:86" *)
    casez (fsm_state)
      /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:87" */
      /* \nmigen.decoding  = "reset/0" */
      1'h0:
        begin
          \n64_ale_h_i$next  = 1'h0;
          \n64_read_i$next  = 1'h1;
        end
      /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:100" */
      /* \nmigen.decoding  = "wait/1" */
      1'h1:
          (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
          casez (state)
            16'h0000:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$57 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_ale_h_i$next  = 1'h1;
                endcase
            16'h0001:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$59 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_ale_l_i$next  = 1'h1;
                endcase
            16'h0002:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$61 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_ale_h_i$next  = 1'h0;
                endcase
            16'h0003:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$63 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_ale_h_i$next  = 1'h0;
                endcase
            16'h0004:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$65 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_ale_l_i$next  = 1'h0;
                endcase
            16'h0005:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$67 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_read_i$next  = 1'h0;
                endcase
            16'h0006:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$69 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_read_i$next  = 1'h1;
                endcase
            16'h0007:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$71 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_read_i$next  = 1'h0;
                endcase
            16'h0008:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$73 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_read_i$next  = 1'h1;
                endcase
            16'h????:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$75 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \n64_read_i$next  = 1'h1;
                endcase
          endcase
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
        begin
          \n64_ale_h_i$next  = 1'h0;
          \n64_read_i$next  = 1'h0;
          \n64_ale_l_i$next  = 1'h0;
        end
    endcase
  end
  always @* begin
    \n64_write_i$next  = n64_write_i;
    (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:86" *)
    casez (fsm_state)
      /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:87" */
      /* \nmigen.decoding  = "reset/0" */
      1'h0:
          \n64_write_i$next  = 1'h1;
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \n64_write_i$next  = 1'h0;
    endcase
  end
  always @* begin
    \cur_addr$next  = cur_addr;
    (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:86" *)
    casez (fsm_state)
      /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:87" */
      /* \nmigen.decoding  = "reset/0" */
      1'h0:
          \cur_addr$next  = 32'd268435456;
      /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:100" */
      /* \nmigen.decoding  = "wait/1" */
      1'h1:
          (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
          casez (state)
            16'h0000:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$77 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$79 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \cur_addr$next  = \$81 [31:0];
                      endcase
                endcase
            16'h0001:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$84 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$86 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \cur_addr$next  = \$88 [31:0];
                      endcase
                endcase
            16'h0002:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$91 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$93 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \cur_addr$next  = \$95 [31:0];
                      endcase
                endcase
            16'h0003:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$98 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$100 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \cur_addr$next  = \$102 [31:0];
                      endcase
                endcase
            16'h0004:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$105 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$107 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \cur_addr$next  = \$109 [31:0];
                      endcase
                endcase
            16'h0005:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$112 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$114 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \cur_addr$next  = \$116 [31:0];
                      endcase
                endcase
            16'h0006:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$119 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$121 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \cur_addr$next  = \$123 [31:0];
                      endcase
                endcase
            16'h0007:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$126 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$128 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \cur_addr$next  = \$130 [31:0];
                      endcase
                endcase
            16'h0008:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$133 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$135 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \cur_addr$next  = \$137 [31:0];
                      endcase
                endcase
            16'h????:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$140 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$142 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \cur_addr$next  = \$144 [31:0];
                      endcase
                endcase
          endcase
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \cur_addr$next  = 32'd0;
    endcase
  end
  always @* begin
    \counter$next  = counter;
    (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:86" *)
    casez (fsm_state)
      /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:87" */
      /* \nmigen.decoding  = "reset/0" */
      1'h0:
          \counter$next  = 16'h0000;
      /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:100" */
      /* \nmigen.decoding  = "wait/1" */
      1'h1:
          (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
          casez (state)
            16'h0000:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$147 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \counter$next  = 16'h0000;
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:112" */
                  default:
                      \counter$next  = \$149 [15:0];
                endcase
            16'h0001:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$152 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \counter$next  = 16'h0000;
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:112" */
                  default:
                      \counter$next  = \$154 [15:0];
                endcase
            16'h0002:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$157 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \counter$next  = 16'h0000;
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:112" */
                  default:
                      \counter$next  = \$159 [15:0];
                endcase
            16'h0003:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$162 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \counter$next  = 16'h0000;
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:112" */
                  default:
                      \counter$next  = \$164 [15:0];
                endcase
            16'h0004:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$167 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \counter$next  = 16'h0000;
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:112" */
                  default:
                      \counter$next  = \$169 [15:0];
                endcase
            16'h0005:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$172 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \counter$next  = 16'h0000;
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:112" */
                  default:
                      \counter$next  = \$174 [15:0];
                endcase
            16'h0006:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$177 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \counter$next  = 16'h0000;
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:112" */
                  default:
                      \counter$next  = \$179 [15:0];
                endcase
            16'h0007:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$182 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \counter$next  = 16'h0000;
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:112" */
                  default:
                      \counter$next  = \$184 [15:0];
                endcase
            16'h0008:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$187 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \counter$next  = 16'h0000;
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:112" */
                  default:
                      \counter$next  = \$189 [15:0];
                endcase
            16'h????:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$192 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      \counter$next  = 16'h0000;
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:112" */
                  default:
                      \counter$next  = \$194 [15:0];
                endcase
          endcase
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \counter$next  = 16'h0000;
    endcase
  end
  always @* begin
    \fsm_state$next  = fsm_state;
    (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:86" *)
    casez (fsm_state)
      /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:87" */
      /* \nmigen.decoding  = "reset/0" */
      1'h0:
          \fsm_state$next  = 1'h1;
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 1'h0;
    endcase
  end
  always @* begin
    \state$next  = state;
    (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:86" *)
    casez (fsm_state)
      /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:100" */
      /* \nmigen.decoding  = "wait/1" */
      1'h1:
          (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
          casez (state)
            16'h0000:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$197 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$202 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \state$next  = 16'h0000;
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:110" */
                        default:
                            \state$next  = \$204 [15:0];
                      endcase
                endcase
            16'h0001:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$207 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$212 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \state$next  = 16'h0000;
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:110" */
                        default:
                            \state$next  = \$214 [15:0];
                      endcase
                endcase
            16'h0002:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$217 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$222 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \state$next  = 16'h0000;
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:110" */
                        default:
                            \state$next  = \$224 [15:0];
                      endcase
                endcase
            16'h0003:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$227 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$232 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \state$next  = 16'h0000;
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:110" */
                        default:
                            \state$next  = \$234 [15:0];
                      endcase
                endcase
            16'h0004:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$237 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$242 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \state$next  = 16'h0000;
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:110" */
                        default:
                            \state$next  = \$244 [15:0];
                      endcase
                endcase
            16'h0005:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$247 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$252 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \state$next  = 16'h0000;
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:110" */
                        default:
                            \state$next  = \$254 [15:0];
                      endcase
                endcase
            16'h0006:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$257 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$262 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \state$next  = 16'h0000;
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:110" */
                        default:
                            \state$next  = \$264 [15:0];
                      endcase
                endcase
            16'h0007:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$267 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$272 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \state$next  = 16'h0000;
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:110" */
                        default:
                            \state$next  = \$274 [15:0];
                      endcase
                endcase
            16'h0008:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$277 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$282 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \state$next  = 16'h0000;
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:110" */
                        default:
                            \state$next  = \$284 [15:0];
                      endcase
                endcase
            16'h????:
                (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" *)
                casez (\$287 )
                  /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:101" */
                  1'h1:
                      (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" *)
                      casez (\$292 )
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:107" */
                        1'h1:
                            \state$next  = 16'h0000;
                        /* src = "/home/stary/develop/n64/gateware/nmigen/test.py:110" */
                        default:
                            \state$next  = \$294 [15:0];
                      endcase
                endcase
          endcase
    endcase
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \state$next  = 16'h0000;
    endcase
  end
  assign \$3  = \$6 ;
  assign \$10  = \$13 ;
  assign \$17  = \$20 ;
  assign \$24  = \$25 ;
  assign \$29  = \$30 ;
  assign \$34  = \$35 ;
  assign \$39  = \$40 ;
  assign \$44  = \$45 ;
  assign \$49  = \$50 ;
  assign \$54  = \$55 ;
  assign \$81  = \$82 ;
  assign \$88  = \$89 ;
  assign \$95  = \$96 ;
  assign \$102  = \$103 ;
  assign \$109  = \$110 ;
  assign \$116  = \$117 ;
  assign \$123  = \$124 ;
  assign \$130  = \$131 ;
  assign \$137  = \$138 ;
  assign \$144  = \$145 ;
  assign \$149  = \$150 ;
  assign \$154  = \$155 ;
  assign \$159  = \$160 ;
  assign \$164  = \$165 ;
  assign \$169  = \$170 ;
  assign \$174  = \$175 ;
  assign \$179  = \$180 ;
  assign \$184  = \$185 ;
  assign \$189  = \$190 ;
  assign \$194  = \$195 ;
  assign \$199  = \$200 ;
  assign \$204  = \$205 ;
  assign \$209  = \$210 ;
  assign \$214  = \$215 ;
  assign \$219  = \$220 ;
  assign \$224  = \$225 ;
  assign \$229  = \$230 ;
  assign \$234  = \$235 ;
  assign \$239  = \$240 ;
  assign \$244  = \$245 ;
  assign \$249  = \$250 ;
  assign \$254  = \$255 ;
  assign \$259  = \$260 ;
  assign \$264  = \$265 ;
  assign \$269  = \$270 ;
  assign \$274  = \$275 ;
  assign \$279  = \$280 ;
  assign \$284  = \$285 ;
  assign \$289  = \$290 ;
  assign \$294  = \$295 ;
endmodule

(* generator = "nMigen" *)
(* \nmigen.hierarchy  = "top.U$$0.U$$0.read_edge" *)
module read_edge(rst, clk, fall, n64__read);
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:14" *)
  wire \$1 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:14" *)
  wire \$3 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:15" *)
  wire \$5 ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:15" *)
  wire \$7 ;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input clk;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:6" *)
  output fall;
  reg fall = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:6" *)
  reg \fall$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:11" *)
  reg last = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:11" *)
  reg \last$next ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  input n64__read;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:7" *)
  reg rise = 1'h0;
  (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:7" *)
  reg \rise$next ;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input rst;
  assign \$1  = ~ (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:14" *) n64__read;
  assign \$3  = \$1  & (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:14" *) last;
  assign \$5  = ~ (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:15" *) last;
  assign \$7  = n64__read & (* src = "/home/stary/develop/n64/gateware/nmigen/misc.py:15" *) \$5 ;
  always @(posedge clk)
      rise <= \rise$next ;
  always @(posedge clk)
      fall <= \fall$next ;
  always @(posedge clk)
      last <= \last$next ;
  always @* begin
    \last$next  = n64__read;
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \last$next  = 1'h0;
    endcase
  end
  always @* begin
    \fall$next  = \$3 ;
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \fall$next  = 1'h0;
    endcase
  end
  always @* begin
    \rise$next  = \$7 ;
    (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \rise$next  = 1'h0;
    endcase
  end
endmodule

(* generator = "nMigen" *)
(* top =  1  *)
(* \nmigen.hierarchy  = "top" *)
module top(rst, clk);
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  wire [15:0] \U$$0_n64__ad_i ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  wire [15:0] \U$$0_n64__ad_o ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  wire \U$$0_n64__ad_oe ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  wire \U$$0_n64__ale_h ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  wire \U$$0_n64__ale_l ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  wire \U$$0_n64__read ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  wire [12:0] \U$$0_sdram__addr ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  wire [1:0] \U$$0_sdram__ba ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  wire \U$$0_sdram__cas ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  wire \U$$0_sdram__cke ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  wire \U$$0_sdram__cs ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  wire [15:0] \U$$0_sdram__data_in ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  wire \U$$0_sdram__data_oe ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  wire [15:0] \U$$0_sdram__data_out ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  wire [1:0] \U$$0_sdram__dqm ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  wire \U$$0_sdram__ras ;
  (* src = "/home/stary/develop/n64/gateware/nmigen/sdram.py:5" *)
  wire \U$$0_sdram__we ;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input clk;
  (* src = "/home/stary/develop/n64/gateware/nmigen/cart.py:9" *)
  wire n64__write;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:11" *)
  wire [15:0] n64_data_o;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:15" *)
  wire n64_data_oe;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  wire n64_n64_ale_h_i;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  wire n64_n64_ale_l_i;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  wire [15:0] n64_n64_data_i;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  wire n64_n64_read_i;
  (* src = "/home/stary/develop/n64/gateware/nmigen/test.py:7" *)
  wire n64_n64_write_i;
  (* src = "/home/stary/.local/lib/python3.8/site-packages/nmigen/hdl/ir.py:526" *)
  input rst;
  \U$$0  \U$$0  (
    .clk(clk),
    .n64__ad_i(\U$$0_n64__ad_i ),
    .n64__ad_o(\U$$0_n64__ad_o ),
    .n64__ad_oe(\U$$0_n64__ad_oe ),
    .n64__ale_h(\U$$0_n64__ale_h ),
    .n64__ale_l(\U$$0_n64__ale_l ),
    .n64__read(\U$$0_n64__read ),
    .rst(rst),
    .sdram__addr(\U$$0_sdram__addr ),
    .sdram__ba(\U$$0_sdram__ba ),
    .sdram__cas(\U$$0_sdram__cas ),
    .sdram__cke(\U$$0_sdram__cke ),
    .sdram__cs(\U$$0_sdram__cs ),
    .sdram__data_in(\U$$0_sdram__data_in ),
    .sdram__data_oe(\U$$0_sdram__data_oe ),
    .sdram__data_out(\U$$0_sdram__data_out ),
    .sdram__dqm(\U$$0_sdram__dqm ),
    .sdram__ras(\U$$0_sdram__ras ),
    .sdram__we(\U$$0_sdram__we )
  );
  sdr_wrapper \U$$1  (
    .Addr(\U$$0_sdram__addr ),
    .Ba(\U$$0_sdram__ba ),
    .Cas_n(\U$$0_sdram__cas ),
    .Cke(\U$$0_sdram__cke ),
    .Clk(clk),
    .Cs_n(\U$$0_sdram__cs ),
    .Dqm(\U$$0_sdram__dqm ),
    .Ras_n(\U$$0_sdram__ras ),
    .We_n(\U$$0_sdram__we ),
    .dq_in(\U$$0_sdram__data_out ),
    .dq_oe(\U$$0_sdram__data_oe ),
    .dq_out(\U$$0_sdram__data_in )
  );
  n64 n64 (
    .clk(clk),
    .n64_ale_h_i(n64_n64_ale_h_i),
    .n64_ale_l_i(n64_n64_ale_l_i),
    .n64_data_i(n64_n64_data_i),
    .n64_read_i(n64_n64_read_i),
    .n64_write_i(n64_n64_write_i),
    .rst(rst)
  );
  assign \U$$0_n64__ale_h  = n64_n64_ale_h_i;
  assign \U$$0_n64__ale_l  = n64_n64_ale_l_i;
  assign n64__write = n64_n64_write_i;
  assign \U$$0_n64__read  = n64_n64_read_i;
  assign \U$$0_n64__ad_i  = n64_n64_data_i;
  assign n64_data_oe = \U$$0_n64__ad_oe ;
  assign n64_data_o = \U$$0_n64__ad_o ;
endmodule

